### ISSUE TITLE
Planning for Version 2

### ISSUE THREAD

**Issue by CharliePoole** [TestCentric/TestCentric.Metadata#10]
If Issue #7 is resolved as proposed (Changing the namespace of our API) it would be a breaking change and require release as version 2.0.0. That's a big step. The purpose of this issue is to decide whether to take that step and, if yes, make a general plan for it.

Initially I've made this a question for discussion. Since this library is crucial to the NUnit engine I'm inviting the @nunit/core-team to contribute their ideas in addition to the @TestCentric/gui-team. If we decide to move ahead, this will become an `Epic` incorporating all the individual issues needed to be resolved.

There are a number of such potential issues:

1. The library has not been built for two years and needs to be updated to use current tools. I'm able to build on AppVeyor using Visual Studio 2019 but not on my local system. Of course, it's possible to do small changes without building locally, but it's not a long-term solution.

2. Tools should be upgraded to the latest versions

3. The build script should be updated, possibly using `TestCentric.Cake.Recipe` so that more steps are automated.

4. All projects should to be upgraded to use the simpler SDK format and be built on VS2022.

5. There are currently no unit tests. That's because the history (see README.md) of this library and the fact that many (but not all) methods are unchanged from `Mono.Cecil`, which has its own tests. If it's going to be maintained independently in the long term, tests are needed. Fortunately, they can probably be ported from the existing engine tests.

### Alternative to upgrading

1. Accept issue #7 as a limitation in all the runners using this package.

2. Solve issue #7 in some other way within each runner and (possibly) stop using this package.

--- 

I'd particularly like to hear comments from whoever is going to take over the job of leading the @nunit/engine-team, the biggest user of this library!

**Comment by yaakov-h** [comment]
Did you mean to refer to issue #7 in the alternatives section, rather than #8?

**Comment by CharliePoole** [comment]
Yes - corrected.

**Comment by CharliePoole** [comment]
I haven't had any feedback on this issue, so I'm going ahead with the outlined approach.

**Comment by CharliePoole** [comment]
Steps required to complete...

- [x] #11
- [x] Update build scripts (PR #14 )
- [x] #15
- [x] Resolve #7
